### ISSUE TITLE
How to save and load the npy format model with imagenet-resnet.py?

### ISSUE THREAD

**Issue by JesseYang** [ppwwyyxx/tensorpack#226] opened 2017-04-09 08:27 UTC
The provided [models](https://drive.google.com/drive/folders/0B9IPQTvr2BBkTXBlZmh1cmlnQ0k) for imagenet-resnet.py are in .npy format.  But I didn't find the code for saving or loading npy models in imagenet-resnet.py. There is load-resnet.py, but the [Readme](https://github.com/ppwwyyxx/tensorpack/tree/master/examples/ResNet) says that it is used to load and run the caffe model. Is it possible to use the downloaded [models](https://drive.google.com/drive/folders/0B9IPQTvr2BBkTXBlZmh1cmlnQ0k) with imagenet-resnet.py?

**Comment by ppwwyyxx** [comment] 2017-04-09 09:11
Yes. Just the `--load` option. It works for both npy and the checkpoint.

**Comment by ppwwyyxx** [comment] 2017-04-09 09:15
Sorry. It works only for evaluation.
Because for evaluation it has:
`        session_init=get_model_loader(model_file),`, which supports both format.
However for training it is `        config.session_init = SaverRestore(args.load)`, which only accepts saver checkpoint.

**Comment by ppwwyyxx** [comment] 2017-04-09 09:21
Duplicate of #117 .

**Closed by ppwwyyxx** 2017-04-09 09:21 UTC
