### ISSUE TITLE
Setting session from TrainConfig doesn't seem to work

### ISSUE THREAD

**Issue by rhofour** [ppwwyyxx/tensorpack#220] opened 2017-04-07 12:04 UTC
I've been trying to modify the DQN example to use a TF session config that only uses 45% of the GPU memory (so I can run two processes at once), however despite setting session_creator in the TrainConfig to use a NewSessionCreator with a custom session I still TF requesting all of my GPU's memory.

I saw that custom session support in training was added relatively recently. Is it supposed to be working?

**Comment by ppwwyyxx** [comment] 2017-04-07 15:51
Could you post the relevant code?

**Comment by rhofour** [comment] 2017-04-08 00:05
Here's a tiny patch that shows what I'm trying to do. Running DQN.py with this patch I still see almost all of the memory on my GPU being reserved.

[code.txt](https://github.com/ppwwyyxx/tensorpack/files/907094/code.txt)

**Comment by ppwwyyxx** [comment] 2017-04-08 00:20
The config should get passed to tensorflow successfully. This might be a TF issue or the config is not enough to make it control the memory usage.
The allow_growth option in the config may help.

**Comment by ppwwyyxx** [comment] 2017-04-08 00:29
It works for me.
```
diff --git i/examples/cifar-convnet.py w/examples/cifar-convnet.py
index a8e18dc..8761bb2 100755
--- i/examples/cifar-convnet.py
+++ w/examples/cifar-convnet.py
@@ -10,6 +10,7 @@ import os

 import tensorpack.tfutils.symbolic_functions as symbf
 from tensorpack.tfutils.summary import *
+from tensorpack.tfutils.sesscreate import *
 from tensorpack.utils.gpu import get_nr_gpu

 """
@@ -114,6 +115,13 @@ def get_config(cifar_classnum):
     dataset_train = get_data('train', cifar_classnum)
     dataset_test = get_data('test', cifar_classnum)

+    tf_conf = tf.ConfigProto()
+    tf_conf.gpu_options.per_process_gpu_memory_fraction = 0.05
+    tf_conf.allow_soft_placement = True
+    session_creator = NewSessionCreator(config=tf_conf)
+
+
     def lr_func(lr):
         if lr < 3e-5:
             raise StopTraining()
@@ -127,6 +135,7 @@ def get_config(cifar_classnum):
             StatMonitorParamSetter('learning_rate', 'val_error', lr_func,
                                    threshold=0.001, last_k=10),
         ],
+        session_creator=session_creator,
         max_epoch=150,
     )
```
Then I can see it consumes only a little memory

**Comment by rhofour** [comment] 2017-04-08 00:38
Does it work with DQN? I'm wondering if it's not getting passed all the way
through the trainers.

**Comment by ppwwyyxx** [comment] 2017-04-08 00:44
The backends are the same for all the examples.

**Comment by rhofour** [comment] 2017-04-08 14:38
Ok, just tried on cifar and that seems to work while DQN (still) doesn't. Hopefully later today I can figure out what's different about the two that's causing this.

**Comment by ppwwyyxx** [comment] 2017-04-08 17:11
That's interesting.. I'll try DQN.

**Comment by ppwwyyxx** [comment] 2017-04-08 20:15
Thanks for the pointer! 
But I don't know anywhere a Session would be created earlier. From that thread it looks like the config issue is quite complicated.

**Comment by ppwwyyxx** [comment] 2017-04-10 19:35
btw, I cannot reproduce this in DQN either (at least not in the first epoch).
I'm using some nightly prebuilt version of TF I downloaded last week.

**Comment by rhofour** [comment] 2017-04-11 01:24
Huh, that's odd. It's easily reproducible for me and happens right from the first epoch. I'm running a version of TF I compiled, but not that recently. I'll switch to the latest RC in the next few days and see if it's fixed for me.

**Comment by ppwwyyxx** [comment] 2017-05-04 12:50
User reported that this is fixed after reinstalling TF. Closing.

**Closed by ppwwyyxx** 2017-05-04 12:50 UTC
