### ISSUE TITLE
Augment boxes (feature request)

### ISSUE THREAD

**Issue by haamoon** [ppwwyyxx/tensorpack#334] opened 2017-07-16 22:32 UTC
Having an augment Image + BBox components to the tensorpack would be helpful for detection task. Maybe adding a function to Augmentor to also augment points or have _get_augment_params return a class that can also get you the transformation function.

**Comment by ppwwyyxx** [comment] 2017-07-17 00:24
The `_fprop_coord` method was originally designed for this. But I never found time to implement it.

**Comment by haamoon** [comment] 2017-07-17 03:21
I'd be happy to do this. Tell me what was the original design you had in mind.

**Comment by ppwwyyxx** [comment] 2017-07-17 04:06
Just did a rename because the original name (which I probably made a year ago) wasn't very good.

Thanks a lot for helping! The design is like the following (and you can certainly make suggestions):
1. If some augmentor changes geometry of an image (more precisely, change the coordinates of pixels), it should implement `_augment_coords(self, coords, param)`, where:
`coords` is an `nx2` (or 2xn, whatever) array of (x, y) __floating point__ coordinates.
`param` is the augmentation parameters returned by `_get_augment_params`.
And returns the new `coords`.

2. Implement this method for `AugmentorList` as well, which basically calls `_augment_coords` on all the augmentors one by one.

3. A DataFlow `AugmentImageCoordinates`, which maps every datapoint of an existing dataflow by the following:
```python
def func(dp):
    img, coords = dp[image_index], dp[coords_index]
    im, prms = self.augs._augment_return_params(im)
    dp[image_index] = im
    coords = self.augs._augment_coords(coords, prms)
    dp[coords_index] = coords
    return dp
```
The existing `AugmentImageComponents` should be a good reference.

Some notes:
1. bounding box is a collection of coordinates, and there are other coordinate-based tasks that don't use bounding boxes (e.g. keypoint localization, non-rectangular bounding box, etc). So it's better to use coordinates.
2. Coordinates rounding error can lead to significant degradation in performance, so it's important to use floating point coordinates, and always consider a pixel as a square rather than a point. It's a bug that some open-source implementations of RCNN doesn't take this into account. For example, for a 4x4 image, the top-left corner point is (0,0), bottom-right corner point is (4,4). The center point of the first pixel is (0.5, 0.5), etc. 
Actually this probably makes implementation easier than integer coordinates. For example a resize will be just a simple scaling of coordinates.

**Comment by haamoon** [comment] 2017-07-17 20:06
So for crop it should looks like this:

def _augment_coords(self, coords, param):
    h0, w0 = param
    #coords = np.copy(coords)
   # change x
    coords[:, 0] = coords[:, 0] - w0
    # change y
    coords[:, 1] = coords[:, 1] - h0    
    return coords

I assume we can directly change coords and similar to AugmentImageComponents copying data will be handled in AugmentImageCoordinates. Can we assume coords are always numpy arrays? Any need to do a type check? And I agree with the notes.

**Comment by ppwwyyxx** [comment] 2017-07-17 20:15
Yes. I think it's OK to change it in-place which is currently the way how images are augmented.
I think assuming numpy arrays is fine, similar to what have been done for images.

**Comment by haamoon** [comment] 2017-07-17 21:44
How do you want to change MapImage? Should it receive two functions? one for mapping image array and one (optional) for mapping coordinates? In case second function is None should we do identity mapping or throw not implemented exception?

**Comment by ppwwyyxx** [comment] 2017-07-17 22:11
To simplify things, I think for now you can leave it the way it is. And in the future we can either add support of coordinate mapping to it, or improve documents saying that `MapImage` doesn't support coordinate mapping.

**Comment by haamoon** [comment] 2017-07-18 04:46
Take a look at #335. Let me know what you think.

**Comment by ppwwyyxx** [comment] 2017-07-18 21:49
Closed by #335. Thanks again for the PR!

**Closed by ppwwyyxx** 2017-07-18 21:49 UTC
Labels: feature

**Comment by ppwwyyxx** [comment] 2017-08-17 09:19
One caveat of the current design: 
Assuming you have box parameterized as (x1, y1, x2, y2), after a horizontal flip, coordinates are mapped to (x1', y1', x2', y2'), but this is not a valid bounding box anymore. The actual bounding box should become (x2', y1, x1', y2).
I don't know if there is any better way to handle this other than letting the user do it. In general the problem is that the different coordinates in the Nx2 array might have some structure that can be broken by the augmentor -- so probably the user do have to take care of it manually.

**Comment by ppwwyyxx** [comment] 2017-08-17 09:26
Maybe one way is to add the `_augment_boxes` method, but let it call `_augment_coords` by default. Then only the rare cases such as flip & transpose needs to be dealt with.

**Comment by haamoon** [comment] 2017-08-17 22:16
I used a simple layer to convert the point coordinates to the box coordinates. It also makes sure box coordinates are inside the image:
```
@layer_register()
def convert_bboxes(bottoms):
    box_coords, w, h = bottoms
    shape = tf.shape(box_coords)
    xs = tf.reshape(box_coords[:, :, 0], [shape[0], -1, 4], name = 'reshape-xs')
    ys = tf.reshape(box_coords[:, :, 1], [shape[0], -1, 4], name = 'reshape-ys')

    # Change coordinates to what rcnn uses
    # Equivalent to tf.round(xs - 0.5)
    xs = tf.round(xs - .5)
    ys = tf.round(ys - .5)

    x1 = tf.reduce_min(xs, axis=-1, keep_dims=True, name='minx')
    x2 = tf.reduce_max(xs, axis=-1, keep_dims=True, name='maxx')
    y1 = tf.reduce_min(ys, axis=-1, keep_dims=True, name='miny')
    y2 = tf.reduce_max(ys, axis=-1, keep_dims=True, name='maxy')

    x1 = tf.clip_by_value(x1, .0, tf.to_float(w))
    x2 = tf.clip_by_value(x2, .0, tf.to_float(w))
    y1 = tf.clip_by_value(y1, .0, tf.to_float(h))
    y2 = tf.clip_by_value(y2, .0, tf.to_float(h))
    bbox = tf.concat(axis = 2, values=[x1,y1,x2,y2])
    return bbox
```
Since the same function could be used for any type of augmentation (including rotation and more complicated ones), I think having a separate helper function for that would be more convenient.

**Comment by ppwwyyxx** [comment] 2017-08-17 22:21
Are you saying that you parameterize a bounding box as 8 floats (instead of 4)? i.e. (x1, y1, ...., x4, y4) . That's the only way transformed points can be converted to a box.

**Comment by haamoon** [comment] 2017-08-17 22:27
Yes, that is what I did.

**Comment by ppwwyyxx** [comment] 2017-08-17 22:46
Thanks! I like this solution.
