### ISSUE TITLE
There is an error working on 4 GPUs

### ISSUE THREAD

**Issue by ChenYunying** [ppwwyyxx/tensorpack#533] opened 2017-12-01 07:05 UTC
The code works with 2 GPUs. When I tried to use 4 GPUs, the error is as follow:

 tensorflow/core/framework/op_kernel.cc:1192] Internal: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices, status: invalid resource handle
Traceback (most recent call last):
  File "inception-bn.py", line 198, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainer(get_nr_gpu()))
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/trainv1/interface.py", line 11, in launch_train_with_config
    old_launch(config, trainer)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/interface.py", line 92, in launch_train_with_config
    config.steps_per_epoch, config.starting_epoch, config.max_epoch)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 249, in train
    self.initialize(session_creator, session_init)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/argtools.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 177, in initialize
    self.sess = session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 425, in create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 283, in prepare_session
    local_init_success, msg = self._try_run_local_init_op(sess)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 481, in _try_run_local_init_op
    is_ready_for_local_init, msg = self._model_ready_for_local_init(sess)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 466, in _model_ready_for_local_init
    "Model not ready for local init")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 508, in _ready
    ready_value = sess.run(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 896, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1279, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1298, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices, status: invalid resource handle
	 [[Node: report_uninitialized_variables_1/boolean_mask/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](report_uninitialized_variables_1/boolean_mask/Reshape_1/_1261)]]
	 [[Node: report_uninitialized_variables_1/boolean_mask/Squeeze/_1263 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1259_report_uninitialized_variables_1/boolean_mask/Squeeze", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'report_uninitialized_variables_1/boolean_mask/Where', defined at:
  File "inception-bn.py", line 198, in <module>
    launch_train_with_config(config, SyncMultiGPUTrainer(get_nr_gpu()))
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/trainv1/interface.py", line 11, in launch_train_with_config
    old_launch(config, trainer)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/interface.py", line 92, in launch_train_with_config
    config.steps_per_epoch, config.starting_epoch, config.max_epoch)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 249, in train
    self.initialize(session_creator, session_init)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/argtools.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 177, in initialize
    self.sess = session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 416, in create_session
    self._scaffold.finalize()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 196, in finalize
    default_ready_for_local_init_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 258, in get_or_default
    op = default_constructor()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 193, in default_ready_for_local_init_op
    variables.global_variables())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/tf_should_use.py", line 170, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/variables.py", line 1325, in report_uninitialized_variables
    return array_ops.boolean_mask(variable_names_tensor, variables_mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1127, in boolean_mask
    return _apply_mask_1d(tensor, mask)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1099, in _apply_mask_1d
    indices = squeeze(where(mask), squeeze_dims=[1])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 2350, in where
    return gen_array_ops.where(input=condition, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3937, in where
    result = _op_def_lib.apply_op("Where", input=input, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2576, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): WhereOp: Could not launch cub::DeviceReduce::Sum to count number of true indices, status: invalid resource handle
	 [[Node: report_uninitialized_variables_1/boolean_mask/Where = Where[_device="/job:localhost/replica:0/task:0/gpu:0"](report_uninitialized_variables_1/boolean_mask/Reshape_1/_1261)]]
	 [[Node: report_uninitialized_variables_1/boolean_mask/Squeeze/_1263 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_1259_report_uninitialized_variables_1/boolean_mask/Squeeze", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

What does it mean? Thank you!

**Comment by ppwwyyxx** [comment] 2017-12-01 08:18
Please tell me __what you did__ as mentioned in the [issue template](https://github.com/ppwwyyxx/tensorpack/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by PatWie** [comment] 2017-12-06 22:03
This is a an issue from a [cub primitive](https://nvlabs.github.io/cub/) usually used in CUDA kernels and it is very likely to be caused by a TF issue itself.

**Comment by ppwwyyxx** [comment] 2017-12-09 19:11
Closing because necessary information about the bug wasn't provided. 
It's very likely that upgrading TF will just solve this issue.

**Closed by ppwwyyxx** 2017-12-09 19:11 UTC
