### ISSUE TITLE
DoReFa-Net:  How to see the trained weights and bias  ？

### ISSUE THREAD

**Issue by MrLinNing** [ppwwyyxx/tensorpack#700] opened 2018-03-19 03:22 UTC
![image](https://user-images.githubusercontent.com/24288811/37576494-b302e42a-2b67-11e8-8ab4-e594d1998984.png)

![image](https://user-images.githubusercontent.com/24288811/37576516-cfa08948-2b67-11e8-8b38-3ed2023db1fe.png)

**Comment by ppwwyyxx** [comment] 2018-03-19 03:29
1. `import_meta_graph` and `saver.restore` is not the best tool for reading a TF checkpoint. You can use `tf.train.NewCheckpointReader` instead.
2. To use `import_meta_graph` you'll need the `clear_devices` option.

I'm closing it since this is a question unrelated to tensorpack. You can follow up if you still have questions.

**Closed by ppwwyyxx** 2018-03-19 03:29 UTC

**Comment by MrLinNing** [comment] 2018-03-19 12:45
Thank you very much,  Yuxin Wu! I used your method, and it works well!
I have read your paper DoReFa-Net, and I run the python script  svhn-digit-dorefa.py --dorefa 1,2,4. It seems that  trained weights is not 1 bits which can represent 2 different real values but have many different real values in the first figure. Can you detail more about it?
Besides, what does the W-rms: 1.1019  mean in  param-summary/conv2/W-rms: 1.1019 ?
I am looking forward to your reply, thank your :) !
![image](https://user-images.githubusercontent.com/24288811/37596140-30c96098-2bb6-11e8-9c29-6a916d83b622.png)
![image](https://user-images.githubusercontent.com/24288811/37596193-5b001b4a-2bb6-11e8-8e66-46729559efd0.png)

**Comment by ppwwyyxx** [comment] 2018-03-19 14:49
What's saved in the checkpoint is `W`, not `W_b`. Duplicate of #573.

**Comment by MrLinNing** [comment] 2018-03-20 08:49
Thank you very much for your patience! 
There is a problem that has troubled me for a long time. When `bitW=2`, the quantized output is 4 `（2^2）` different real numbers instead of `4bit `fixed-point integers, which cannot satisfy the condition of Formula 3 in the paper. Can you help me understand how to use Formula 3? Thank you！
![image](https://user-images.githubusercontent.com/24288811/37644156-d34f3890-2c5d-11e8-97f5-8dbaf539989c.png)
![image](https://user-images.githubusercontent.com/24288811/37644259-28d39086-2c5e-11e8-8655-d3f9243b7b2e.png)
![image](https://user-images.githubusercontent.com/24288811/37644228-056685ea-2c5e-11e8-96b0-ceb80e222fb4.png)

**Comment by ppwwyyxx** [comment] 2018-03-20 11:52
(a * x + b) \dot (c * y + d) = a*c* (x \dot y) + a * d * sum(x) + b * c * sum(y) + bd

**Comment by MrLinNing** [comment] 2018-03-21 10:53
Sorry,  I didn't understand your reply. What I want to say is that the final quantized output  `Wb` is not fixed-point integer according to your code. But the input value X,Y of formula 3 is the fixed point number.

**Comment by ppwwyyxx** [comment] 2018-03-21 12:45
Also see https://github.com/ppwwyyxx/tensorpack/issues/27#issuecomment-255015193
