### ISSUE TITLE
issue with tensorboard

### ISSUE THREAD

**Issue by deeplearningmachine** [ppwwyyxx/tensorpack#311] opened 2017-06-23 15:54 UTC
Get "No graph definition files were found." in tensorboard when running the cifar10-resnet.py?
Anyone has similar issue?

**Comment by ppwwyyxx** [comment] 2017-06-23 16:01
Cannot reproduce your problem. Have you seen logs like "Model saved to train_log/cifar10-resnet/model-390"? It'll appear after the first epoch.

**Comment by deeplearningmachine** [comment] 2017-06-23 16:05
yes, the code works perfectly.

100%|#####################################################################################|390/390[01:11<00:00, 4.76it/s]
[0623 12:07:18 @base.py:254] Epoch 11 (global_step 4290) finished, time:71.23 sec.
[0623 12:07:19 @saver.py:66] Model saved to _test_/model-4290.
100%|#######################################################################################|79/79[00:05<00:00,14.95it/s]
[0623 12:07:24 @monitor.py:294] cross_entropy_loss: 0.39552
[0623 12:07:24 @monitor.py:294] input_queue_size: 50
[0623 12:07:24 @monitor.py:294] learning_rate: 0.1
[0623 12:07:24 @monitor.py:294] train_error: 0.13705
[0623 12:07:24 @monitor.py:294] val_error: 0.1673
[0623 12:07:24 @monitor.py:294] validation_cost: 0.85421
[0623 12:07:24 @monitor.py:294] wd_cost: 0.33984
[0623 12:07:24 @group.py:43] Callbacks took 5.392 sec in total. InferenceRunner: 5.286sec
[0623 12:07:24 @base.py:167] Start Epoch 12 ...
100%|#####################################################################################|390/390[01:11<00:00, 4.82it/s]
[0623 12:08:36 @base.py:254] Epoch 12 (global_step 4680) finished, time:71.73 sec.
[0623 12:08:36 @saver.py:66] Model saved to _test_/model-4680.
100%|#######################################################################################|79/79[00:05<00:00,15.07it/s]
[0623 12:08:41 @monitor.py:294] cross_entropy_loss: 0.38523
[0623 12:08:41 @monitor.py:294] input_queue_size: 50
[0623 12:08:41 @monitor.py:294] learning_rate: 0.1
[0623 12:08:41 @monitor.py:294] train_error: 0.13363
[0623 12:08:41 @monitor.py:294] val_error: 0.1769
[0623 12:08:41 @monitor.py:294] validation_cost: 0.87989
[0623 12:08:41 @monitor.py:294] wd_cost: 0.3224
[0623 12:08:41 @group.py:43] Callbacks took 5.347 sec in total. InferenceRunner: 5.243sec
[0623 12:08:41 @base.py:167] Start Epoch 13 ...
100%|#####################################################################################|390/390[01:11<00:00, 4.95it/s]
[0623 12:09:53 @base.py:254] Epoch 13 (global_step 5070) finished, time:71.64 sec.
[0623 12:09:53 @saver.py:66] Model saved to _test_/model-5070.
100%|#######################################################################################|79/79[00:05<00:00,14.82it/s]
[0623 12:09:58 @monitor.py:294] cross_entropy_loss: 0.34247
[0623 12:09:58 @monitor.py:294] input_queue_size: 50
[0623 12:09:58 @monitor.py:294] learning_rate: 0.1
[0623 12:09:58 @monitor.py:294] train_error: 0.11957
[0623 12:09:58 @monitor.py:294] val_error: 0.1642
[0623 12:09:58 @monitor.py:294] validation_cost: 0.80837
[0623 12:09:58 @monitor.py:294] wd_cost: 0.30838
[0623 12:09:58 @group.py:43] Callbacks took 5.416 sec in total. InferenceRunner: 5.334sec
[0623 12:09:58 @base.py:167] Start Epoch 14 ...

**Comment by deeplearningmachine** [comment] 2017-06-23 16:13
Issue related to my browser? Got "Rats! WebGL hits a snag!" error from Chrome.

**Comment by ppwwyyxx** [comment] 2017-06-24 19:06
Maybe.
tensorpack did nothing special about saving the events. I think it's not a bug in this project. Closing for now.

**Closed by ppwwyyxx** 2017-06-24 19:06 UTC
