### ISSUE TITLE
cifar10-resnet.py: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yhlleo** [ppwwyyxx/tensorpack#173] opened 2017-03-03 05:48 UTC
Hi, 

When I was training the model of `cifar10-resnet.py`, the code always stopped at this place:

`tensorpack/dataflow/dataset/cifar.py, line 45 read_cifar() `.

When the loop--`for fname in filenames:`--gone to the fifth file `data_batch_5` and the subloop--`for k in range(IMG_NUM):` gone o `k=5136`, something wrong occurred:

```
...
k = 5135
k = 5136
Segmentation fault (core dumped)
```

(Here, I print the value of k during the loop). Then the program was over.

Have you met such a problem?

**Comment by ppwwyyxx** [comment] 2017-03-03 06:00
I couldn't reproduce this problem. Note that there are multiple threads running so it's unlikely it is a problem with data reading, but more likely to be in training.

Could you try if the simple examples (mnist-convnet.py, cifar-convnet.py) can run?
And how do you install opencv? Are you using anaconda?

**Comment by yhlleo** [comment] 2017-03-03 06:15
I tried the another example `cifar-convnet.py`, but the same problem occurred.  Before the `cifar`,  I have test the example `HED`, it runs well. 

I re-downloaded the file `cifar-10-python.tar.gz`  to exclude that the file is damaged.

---

I have installed OpenCV 3.1, CUDA 8.0, cuDNN 5.1( without using anaconda ).

**Comment by ppwwyyxx** [comment] 2017-03-03 06:22
How do you install opencv?
And could you try running without GPU to see if the error occurs? (use CUDA_VISIBLE_DEVICES=)

**Comment by yhlleo** [comment] 2017-03-03 06:27
In fact, I traced debug the problem, it's just a problem of data reading. (The program was still in the data loading stage before the training phase, when it occurred.)

----

I installed the OpenCV according to the guide: [OpenCV: Installation in Linux](http://docs.opencv.org/3.1.0/d7/d9f/tutorial_linux_install.html#gsc.tab=0).

**Comment by ppwwyyxx** [comment] 2017-03-03 06:28
Could you post the full log so I can see which stage it was in?

**Comment by yhlleo** [comment] 2017-03-03 06:38
I added some `print` in the original code:

```
# tensorpack/dataflow/dataset/cifar.py

...
        for k in range(IMG_NUM):
            img = data[k].reshape(3, 32, 32)
            img = np.transpose(img, [1, 2, 0])
            ret.append([img, label[k]])
            #print k
        print fname, len(ret)
    print "read_cifar done"
```

Output: 
```
...
/home/swoda/tensorpack_data/cifar10_data/cifar-10-batches-py/data_batch_1 10000
/home/swoda/tensorpack_data/cifar10_data/cifar-10-batches-py/data_batch_2 20000
/home/swoda/tensorpack_data/cifar10_data/cifar-10-batches-py/data_batch_3 30000
/home/swoda/tensorpack_data/cifar10_data/cifar-10-batches-py/data_batch_4 40000
Segmentation fault (core dumped)
```

Then, I printed the `k`:

```
...
5105
5106
5107
5108
5109
Segmentation fault (core dumped)
```

It seems that the the location of the error is different sometimes.

**Comment by ppwwyyxx** [comment] 2017-03-03 06:43
If this is where it crashes I have no clue now. 
```
python2 -c "from tensorpack import dataset; c = dataset.Cifar10('train')" 
```
should also crash for you if it really breaks there.

**Comment by yhlleo** [comment] 2017-03-03 06:47
It works by running:

```
python2 -c "from tensorpack import dataset; c = dataset.Cifar10('train')" 
```

Output:

```
...
9998
9999
/home/swoda/tensorpack_data/cifar10_data/cifar-10-batches-py/data_batch_5 50000
read_cifar done
```

**Comment by ppwwyyxx** [comment] 2017-03-03 07:06
Did the crash happen when loading training data or validation/test data?
If the latter, could you remove the prefetch (or even the augmentors) in cifar-convnet.py to see if it segfaults?

**Comment by yhlleo** [comment] 2017-03-03 07:19
It happened when loading training data.

It made no effect with removing the prefetch and augmentors.

**Comment by ppwwyyxx** [comment] 2017-03-03 07:21
Then `cifar-convnet.py` should be equivalent to the following:
```python
import tensorflow as tf
import argparse
import numpy as np
import os
from tensorpack import *
import tensorpack.tfutils.symbolic_functions as symbf
from tensorpack.tfutils.summary import *
from tensorpack.utils.gpu import get_nr_gpu
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
with tf.Graph().as_default():
    logger.auto_set_dir()
    ds = dataset.Cifar10('train')
```

**Comment by ppwwyyxx** [comment] 2017-03-03 07:22
If the above code crashes, could you import cv2 at the first line and try again?

**Comment by yhlleo** [comment] 2017-03-03 07:31
After adding `import cv2` at the first line of `cifar10-resnet.py` and `cifar1-convnet.py`, the problem was solved!

Thank you very much!

**Comment by ppwwyyxx** [comment] 2017-03-03 07:34
OK. I thought this problem was fixed by tensorflow already. Turns out it still happens on some systems.

I'll update some examples to avoid this.

**Closed** 2017-03-03 07:44 UTC
