### ISSUE TITLE
Dorefa alexnet vs alexnet

### ISSUE THREAD

**Issue by a-maci** [ppwwyyxx/tensorpack#165] opened 2017-02-27 08:03 UTC
I noticed alexnet-dorefa's first convolution layer has filter spatial dim of 12x12 - 
`.Conv2D('conv0', 96, 12, stride=4, padding='VALID').`

Alexnet's first CONV layer is 11x11. Is this a discrepancy? 

https://github.com/BVLC/caffe/wiki/Models-accuracy-on-ImageNet-2012-val says alexnet gives top-1 accuracy = 0.569 (error = 43.1). When I run alexnet-dorefa with 32,32,32 I get error-rate 45.0% (2% higher than reported in the above webpage). Is this because of above descrepancy?

**Comment by ppwwyyxx** [comment] 2017-02-27 08:07
maybe it will cause small performance degradation. there are other differences compared to caffe as well.
duplicate of #54.

**Closed by ppwwyyxx** 2017-02-27 08:07 UTC
