### ISSUE TITLE
Gray scale image feed error using 'ImageFromFile' dataflow

### ISSUE THREAD

**Issue by shuzhangcasia** [ppwwyyxx/tensorpack#78] opened 2016-12-30 09:00 UTC
Support for gray scale image is buggy as the output data has shape (w,h) instead of (w, h, 1)

Should add 
            if self.channel == 1:
                im = im[:,:,None]
on line 39 of tensorpack/dataflow/image.py

**Comment by ppwwyyxx** [comment] 2016-12-30 09:04
This was intended, but yes it might be a bit misleading. Fixed in head.

**Closed** 2016-12-31 06:27 UTC
Labels: bug
