### ISSUE TITLE
I tried to run run-atari.py to evalute 100 episode however I got the following result, do you have any clue to fix it?

### ISSUE THREAD

**Issue by lightaime** [ppwwyyxx/tensorpack#97] opened 2017-01-10 19:53 UTC
Exception gym.error.Error: Error('env has been garbage collected. To keep using a monitor, you must keep around a reference to the env object. (HINT: try assigning the env to a variable in your code.)',) in <bound method AtariEnv.__del__ of <gym.envs.atari.atari_env.AtariEnv object at 0x7f792817b690>> ignored
Exception gym.error.Error: Error('env has been garbage collected. To keep using a monitor, you must keep around a reference to the env object. (HINT: try assigning the env to a variable in your code.)',) in <bound method Monitor.__del__ of <gym.monitoring.monitor.Monitor object at 0x7f792817b650>> ignored

Thank you very much.

**Comment by ppwwyyxx** [comment] 2017-01-10 23:54
This is normal.

**Comment by ppwwyyxx** [comment] 2017-01-12 15:50
Closing since this is a duplicate of #36.

**Closed by ppwwyyxx** 2017-01-12 15:50 UTC

**Comment by lightaime** [comment] 2017-01-14 11:57
Since this error make the result imcomplete, the result won't be able to upload to gym. But it doesn't matter. thank you.

**Comment by ppwwyyxx** [comment] 2017-01-14 12:03
I didn't know that would happen. I was ignoring this error all the time and things are fine.
Maybe there are some changes in gym that make this error matter? I'll try it when I have time.

**Comment by lightaime** [comment] 2017-01-18 17:35
Thank you very much.
